### ISSUE TITLE
v0.4.6 can not replace with ampersand `&`.

### ISSUE THREAD

**Issue by lnwsit** [lukasjarosch/go-docx#22]
In version v0.4.6 can not  replace string contain `&` (ampersand) such as 

code
```
docx.PlaceholderMap{
     "company":  "Test & test"
}
```
word
`{company}`

but v0.4.4 it work

**Comment by lukasjarosch** [comment]
Thank you very much for reporting this ❤️ 

This is most likely due me forgetting to re-add html escaping [here](https://github.com/lukasjarosch/go-docx/commit/6fe91684eaed396ebf9253efafee422fbdadb809#diff-7798eb77ea652cd8a2d4193575a0d64e5de3cbb3d9b683bba6c59808e8bd48a7R58).

I've checked and re-added the esacping and ampersand replacing seems to be working again.
This should be resolved in [v0.4.7](https://github.com/lukasjarosch/go-docx/releases/tag/v0.4.7).

Thank you for using `go-docx`, feel free to open more issues as they arise 😃
