### ISSUE TITLE
How to convert to []byte

### ISSUE THREAD

**Issue by shehuaqigai** [lukasjarosch/go-docx#26]
I need to replace it and call straight back to the file stream

**Comment by lukasjarosch** [comment]
Could you please be a bit more elaborate on what you are trying to do?

**Comment by shehuaqigai** [comment]
wordDocx, docxErr := docx.Open(docxPath)
			if docxErr != nil {
				ctx.StopWithStatus(500)
				return
			}

			replaceMap := docx.PlaceholderMap{
				"year":  "2024",
				"month": "04",
				"day":   "03",
			}
			// replace the keys with values from replaceMap
			docxErr = wordDocx.ReplaceAll(replaceMap)
			if docxErr != nil {
				ctx.StopWithStatus(500)
				return
			}
			ctx.Header("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
			ctx.Header("Content-Disposition", "attachment; filename=example.docx")

			ctx.Write([]byte)//iris.go  I need to type directly back to the file stream, not write to the file

**Comment by lukasjarosch** [comment]
Ahh, i see. Thanks for elaborating.

This should already be possible. You can use [document.Write](https://github.com/lukasjarosch/go-docx/blob/develop/document.go#L352) for that. Something like this should work:

```go
// ...
out := []bytes{}
buf := bytes.NewBuffer(out)
err = wordDocx.Write(buf)

// now you can continue work with just the byte slice of the rendered document
ctx.Write(buf.Bytes())
```

**Comment by shehuaqigai** [comment]
Thank you very much!
