### ISSUE TITLE
PlaceholderMap (or Word) does not adhere to '\n' character

### ISSUE THREAD

**Issue by TheMMMdev** [lukasjarosch/go-docx#9]
It does not seem to be possible to add a 'newline' character (\n or \r\n if you will) within a table cell of a Word table. 

Current formatting: 

```golang
var location string
	for _, host := range res.HostInfo {
		for i := range host.Ports {
			location += (host.Address + ":" + host.Ports[i].PortNumber + " (" + host.Ports[i].Proto + ")" + "\n") // also tried \r\n and \t
		}
	}
```

Output seems only to add some kind of whitespace within the cell:

![locations1](https://user-images.githubusercontent.com/63477464/190634898-b0da6c8f-5a16-457d-9f25-2102f374c2bd.png)

This might be the dumbest issue ever written, so sorry beforehand. Is there any way to enforce this newline?

**Comment by lukasjarosch** [comment]
I'm pretty late to the party, sorry this issue somehow got lost.
I've just quickly added a fix which should produce the correct output for `\n`.

**Comment by DimNS** [comment]
When can I expect a new version with this change?

I also needed to make a multiline text

**Comment by TheMMMdev** [comment]
Hey @lukasjarosch,

Thanks for the merge! However, this does not seem to be working when it's in a table cell. Using the exact code as outlined above, I'm still only getting everything put on one line. Do table cells have different structures?

Cheers,

MMM

**Comment by shadow1163** [comment]
Same issue here, should it reopen?

**Comment by DimNS** [comment]
> Same issue here, should it reopen?

https://github.com/lukasjarosch/go-docx/pull/10
a pull request was applied, but a new version was not created, so in order to get a patch for yourself, you need to use the version from a specific commit: `github.com/lukasjarosch/go-docx v0.4.5-0.20230207135630-ab2f30734eb0`

perhaps this is the reason

**Comment by shadow1163** [comment]
Thanks

**Comment by lukasjarosch** [comment]
Well, shame on me :fearful:. Let there be a new version.

**Comment by lukasjarosch** [comment]
Just pushed tag `v0.4.5` ([link](https://github.com/lukasjarosch/go-docx/releases/tag/v0.4.5)) which includes PR #10 #12 and

I've ran the example again, and confirmed it as working.

![image](https://user-images.githubusercontent.com/3764664/232515587-95fa2c32-b5ee-447a-a5b2-340baa05755c.png)

**template**
![image](https://user-images.githubusercontent.com/3764664/232515697-aa3e596a-b4c4-4ae4-a4c7-1f4c483cbf65.png)

**replaced**
![image](https://user-images.githubusercontent.com/3764664/232515838-8c0b8c8b-f6f8-432e-8f08-3465299ebdd1.png)

Sorry for the inconvenience. If there is still something wrong, just comment again 😃
